### ISSUE TITLE
Close colour picker on click not on release of mouse button

### ISSUE THREAD

**Issue by TilmanK** [opcode81/Sketchers#47] opened 2016-02-04 20:26 UTC

**Comment by opcode81** [comment] 2016-02-07 00:30
This is intended behaviour. The colour picker must be closed explicitly, because selecting a colour does not necessarily end the action, as the selected colour can subsequently be modified in the right section of the control. The control must be closed by selecting the "Choose" action or by clicking outside of the control.

**Closed as completed by opcode81** 2016-02-07 00:30 UTC
